name: Create Release Branch

on:
  schedule:
    # It should be kept in sync with if-condition in jobs
    - cron: '0 6 * * MON' # Storage release
    - cron: '0 6 * * THU' # Proxy release
  workflow_dispatch:
    inputs:
      create-storage-release-branch:
        type: boolean
        description: 'Create Storage release PR'
        required: false
      create-proxy-release-branch:
        type: boolean
        description: 'Create Proxy release PR'
        required: false

# No permission for GITHUB_TOKEN by default; the **minimal required** set of permissions should be granted in each job.
permissions: {}

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  create-storage-release-branch:
    if: ${{ github.event.schedule == '0 6 * * MON' || format('{0}', inputs.create-storage-release-branch) == 'true' }}

    permissions:
      contents: write

    uses: ./.github/workflows/_create-release-pr.yml
    with:
      component-name: 'Storage & Compute'
      release-branch: 'release'
    secrets:
      ci-access-token: ${{ secrets.CI_ACCESS_TOKEN }}

  create-proxy-release-branch:
    if: ${{ github.event.schedule == '0 6 * * THU' || format('{0}', inputs.create-proxy-release-branch) == 'true' }}

    permissions:
      contents: write

    uses: ./.github/workflows/_create-release-pr.yml
    with:
      component-name: 'Proxy'
      release-branch: 'release-proxy'
    secrets:
      ci-access-token: ${{ secrets.CI_ACCESS_TOKEN }}
