name: Report Workflow Stats Batch

on:
  schedule:
    - cron: '25 0 * * *'
    - cron: '25 1 * * 6'

jobs:
  gh-workflow-stats-batch-2h:
    name: GitHub Workflow Stats Batch 2 hours
    if: github.event.schedule == '*/15 * * * *'
    runs-on: ubuntu-22.04
    permissions:
      actions: read
    steps:
    - name: Export Workflow Run for the past 2 hours
      uses: neondatabase/gh-workflow-stats-action@v0.2.1
      with:
        db_uri: ${{ secrets.GH_REPORT_STATS_DB_RW_CONNSTR }}
        db_table: "gh_workflow_stats_neon"
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        duration: '2h'

  gh-workflow-stats-batch-48h:
    name: GitHub Workflow Stats Batch 48 hours
    if: github.event.schedule == '25 0 * * *'
    runs-on: ubuntu-22.04
    permissions:
      actions: read
    steps:
    - name: Export Workflow Run for the past 48 hours
      uses: neondatabase/gh-workflow-stats-action@v0.2.1
      with:
        db_uri: ${{ secrets.GH_REPORT_STATS_DB_RW_CONNSTR }}
        db_table: "gh_workflow_stats_neon"
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        duration: '48h'

  gh-workflow-stats-batch-30d:
    name: GitHub Workflow Stats Batch 30 days
    if: github.event.schedule == '25 1 * * 6'
    runs-on: ubuntu-22.04
    permissions:
      actions: read
    steps:
    - name: Export Workflow Run for the past 30 days
      uses: neondatabase/gh-workflow-stats-action@v0.2.1
      with:
        db_uri: ${{ secrets.GH_REPORT_STATS_DB_RW_CONNSTR }}
        db_table: "gh_workflow_stats_neon"
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        duration: '720h'
